days_counter/urls.py
from django.urls import path
from . import views

app_name = 'days_counter'

urlpatterns = [
    path('', views.view_index, name='index'),
]

days_counter_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('days_counter.urls'), name='index')
]

days_counter/models.py
from django.db import models

# Create your models here.

days_counter/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def view_index(request):
    if(request.POST.get('birthday') and int(request.POST.get('life_expectancy')) != 0):
        birthday = datetime.date.fromisoformat(request.POST.get('birthday'))
        life_expectancy = int(request.POST.get('life_expectancy')) 
        today = datetime.date.today()
        last_date = birthday + datetime.timedelta(days=(life_expectancy * 365))
        total_days = (last_date - birthday).days

        days_lived = (today - birthday).days 
        days_avaliable = (last_date - today).days
        days_lived_percentage = round(days_lived * 100 / total_days, 2) 
        days_left_percentage = round(days_avaliable * 100 / total_days, 2)
        return render(request, 'index.html', context={'days_lived':days_lived, 'days_avaliable': days_avaliable, 'total_days':total_days, 'days_lived_percentage':days_lived_percentage, 'days_left_percentage':days_left_percentage, 'last_date': last_date, 'birthday':birthday.isoformat(), 'life_expectancy':life_expectancy})
    else:
        return render(request, 'index.html', context={'no_data':True})

days_counter/templates/index.html
{% load static %}
<html lang="en">
	<head>
		<title>Days</title>
		<link rel="stylesheet" href="{% static 'style.css' %}" />
		<link rel="icon" href="{% static 'img/totoro.ico' %}" />
		<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
	</head>
	<body>
		{% comment %}data for the chart{% endcomment %}
		<input type="hidden" id="days_lived_percentage" value={{days_lived_percentage}} />
		<input type="hidden" id="days_left_percentage" value={{days_left_percentage}} />
		{% comment %}end of data for the chart{% endcomment %}

		<div id="container">
			<header id="container-header"><p>Days remainder</p></header>
			<div id="container-form">
				<form method="post" action="{% url 'days_counter:index' %}">
					{% csrf_token %}
					<h1>Insert your data:</h1>
					<label>Birthday:</label>
					<input type="date" name="birthday" id="birthday_inp" value="{{birthday}}" required />
					<label>Your Subjective Life expectancy (years): </label>
					<input type="number" name="life_expectancy" id="life_expectancy_inp" value="{{life_expectancy}}" required />
					<button>Calculate</button>
				</form>
			</div>
			<div id="container-image"></div>
			<div id="container-results">
				<h1>Results:</h1>
				<div id="results-graph"></div>
				{% if no_data %}
				<p>Insert information on the left site to calculate your life_expectancy.</p>
	 		{% else %}
			<p id="results-description">You lived <b>{{days_lived}}</b> days of <b>{{total_days}}</b> days, you have left <b>{{days_avaliable}}</b> days, it's <b>{{days_lived_percentage}}%</b> of your life, therefore you have yet <b>{{days_left_percentage}}%</b> so use it proudly. You will probably die on <b>{{last_date}}</b></p>
				{% endif %}
			</div>
			<footer id="container-footer"><p>...</p></footer>
		</div>
		<script src="{% static 'script.js' %}"></script>
	</body>
</html>